<Widgets>:
    Button:
        text: "press me"
        on_release: root.btn()
<P>:
    Label:
        text: "y0u pressed the butt0n"



    TextInput:
        id: sname
        multiline:True
        text: root.showtext()
        pos_hint: {"x":0.1}
        background_color: 0.8,0.4,0.5,1
        size_hint:1, 1




    Button:
        text: "y0u pressed the butt0n"
        size_hint: 0.2, 0.2
        pos_hint: {"x":0.1, "y":0.1}


